Corrected errors in Readme.md
huggingface/huggingface-llama-recipes pull request #80
Opened 2024-10-24 05:52 UTC by Parth4git

Corrected the mistakes in readme.md to increase readability

2024-10-24 17:21 UTC, Parth4git commented
@Vaibhavs10 @ariG23498 Can you Please review my PR

2024-10-25 04:49 UTC, ariG23498 requested changes
Left some minor nits.

2024-10-25 04:49 UTC, ariG23498 commented on .github/README.md
> +#             learning that uses neural networks"}
This is not a mistake. We had asked the model to respond like a pirate.

2024-10-25 04:49 UTC, ariG23498 commented on .github/README.md
> +It is often not enough to run inferences on the model.
Let's revert back to inference as I do not seem to think it is a grammatical error.

2024-10-25 04:49 UTC, ariG23498 commented on .github/README.md
> +## Text Generation Inference (TGI) and API Inference with Llama Models
Let's revert back to `&`

2024-10-25 17:38 UTC, Parth4git commented
Now , Please review the changes you mentioned are implemented. If everything in fine , Please merge the PR
@ariG23498 @pcuenca

2024-10-27 03:47 UTC, Parth4git commented
@ariG23498 ,Please take a look to PR

2024-10-27 23:41 UTC, pcuenca commented
Hi @Parth4git, the people that need to review this PR are already receiving notifications, there's no need to ping them repeatedly about it. If you want to build lasting relationships with others in the community, I'd recommend you try to be patient and respectful of their time and availability.

2024-10-28 04:52 UTC, Parth4git commented
@pcuenca , Yes I respect their time and availability. But just wanted to know about any update PR status , I have participated in Devfest.ai event and only 3 days are left for event to end. If my PR get merged I will get points . That why I wanted to know about status of my PR

2024-10-28 04:57 UTC, ariG23498 approved these changes
Looks good to me.

2024-10-28 04:57 UTC, merged

2024-10-28 05:37 UTC, Parth4git commented
thank you